const QUESTIONS = [
// ═══════════════════════════════════════════
// FOOD & NUTRITION (5 questions)
// ═══════════════════════════════════════════
{id:1,cat:"food",q:"According to FEMA, how many calories per person per day should you plan for in an emergency food supply?",o:["1,200 calories","2,000 calories","3,500 calories","800 calories"],a:1,src:"FEMA / Ready.gov — Build A Kit",exp:"Ready.gov recommends planning for approximately 2,000 calories per person per day in an emergency food supply. Many people underestimate at 1,200 or overestimate at 3,500."},
{id:2,cat:"food",q:"What is the recommended minimum emergency food supply duration according to Ready.gov?",o:["24 hours","48 hours","72 hours (3 days)","1 week (7 days)"],a:2,src:"FEMA / Ready.gov — Build A Kit",exp:"Ready.gov recommends keeping at least a 72-hour (3-day) supply of non-perishable food. While longer supplies are better, 72 hours is the minimum standard."},
{id:3,cat:"food",q:"Which of these foods does the Red Cross recommend AVOIDING in an emergency kit?",o:["Canned tuna and crackers","Peanut butter and jelly","Foods that require refrigeration after opening","Granola bars and dried fruit"],a:2,src:"American Red Cross — Survival Kit Supplies",exp:"The Red Cross advises against including foods that require refrigeration after opening, since power outages are common during emergencies. This is a common oversight when building kits."},
{id:4,cat:"food",q:"After a power outage, how long will food in a full freezer stay safe if the door is kept closed?",o:["About 6 hours","About 48 hours","About 12 hours","About 1 week"],a:1,src:"USDA / FoodSafety.gov — Food Safety During Power Outages",exp:"A full freezer will keep food safe for approximately 48 hours (24 hours if half full) as long as the door remains closed. Many people open the door to check, which reduces this time significantly."},
{id:5,cat:"food",q:"What does the USDA recommend as the safe minimum internal temperature for all reheated leftovers?",o:["140°F (60°C)","165°F (74°C)","120°F (49°C)","200°F (93°C)"],a:1,src:"USDA / FoodSafety.gov — Safe Minimum Cooking Temperatures",exp:"The USDA recommends reheating all leftovers to 165°F (74°C). The common mistake is 140°F, which is the safe holding temperature, not the reheating temperature.",media:{type:"image",url:"images/food-emergency-kit.svg",alt:"Diagram of recommended 72-hour emergency food supply items",caption:"A well-stocked 72-hour emergency food kit includes non-perishable, high-calorie items (Source: FEMA / Ready.gov)"}},

// ═══════════════════════════════════════════
// WATER (5 questions)
// ═══════════════════════════════════════════
{id:6,cat:"water",q:"How much water per person per day does Ready.gov recommend storing for emergencies?",o:["Half a gallon","One gallon","Two gallons","Three gallons"],a:1,src:"FEMA / Ready.gov — Water",exp:"Ready.gov recommends one gallon of water per person per day for drinking and sanitation. Children, nursing mothers, and sick people may need more. A common error is thinking half a gallon is sufficient."},
{id:7,cat:"water",q:"According to the CDC, how long should you boil water to purify it at elevations below 6,500 feet?",o:["5 minutes at a full boil","1 minute at a rolling boil","10 minutes at a simmer","30 seconds at a rolling boil"],a:1,src:"CDC — Making Water Safe in an Emergency",exp:"The CDC recommends bringing water to a rolling boil for 1 minute at elevations below 6,500 feet (3 minutes above that). The old belief that you need to boil for 5-10 minutes is a common misconception — 1 minute of rolling boil kills pathogens effectively.",media:{type:"image",url:"images/water-purification-methods.svg",alt:"Diagram showing water purification by boiling with step-by-step instructions",caption:"Boiling is the most reliable method to make water safe (Source: CDC)"}},
{id:8,cat:"water",q:"If you cannot boil water, what does the EPA recommend as an alternative disinfection method?",o:["Adding 1 cup of vinegar per gallon","Adding 8 drops (⅛ teaspoon) of unscented household bleach per gallon","Adding a tablespoon of hydrogen peroxide per gallon","Adding a tablespoon of rubbing alcohol per gallon"],a:1,src:"EPA — Emergency Disinfection of Drinking Water",exp:"The EPA recommends adding 8 drops (about ⅛ teaspoon) of regular unscented liquid household bleach per gallon of clear water. Vinegar, hydrogen peroxide, and rubbing alcohol are not effective alternatives."},
{id:9,cat:"water",q:"According to Ready.gov, how long can commercially bottled water be safely stored if kept in proper conditions?",o:["6 months maximum","Indefinitely if unopened and properly stored","1 year at most","2 years at most"],a:1,src:"FEMA / Ready.gov — Water",exp:"Ready.gov states that commercially bottled water can be stored indefinitely if kept unopened in a cool, dark place. The expiration dates on bottles are for quality, not safety. Many people discard perfectly safe water based on expiration dates."},
{id:10,cat:"water",q:"What is the primary danger of drinking untreated water from streams or lakes during an emergency?",o:["Heavy metal poisoning from mineral deposits","Waterborne pathogens like Giardia, Cryptosporidium, and bacteria","Chemical contamination from dissolved oxygen","Excessive mineral content causing kidney stones"],a:1,src:"CDC — Wilderness Water Disinfection",exp:"The primary danger is waterborne pathogens including parasites (Giardia, Cryptosporidium), bacteria (E. coli, Salmonella), and viruses. Even clear-looking water can harbor these organisms."},

// ═══════════════════════════════════════════
// SHELTER (5 questions)
// ═══════════════════════════════════════════
{id:11,cat:"shelter",q:"According to FEMA, what is the most immediate threat to survival in a cold-weather emergency without shelter?",o:["Dehydration from dry cold air","Hypothermia from exposure","Frostbite on extremities","Starvation from increased calorie burn"],a:1,src:"FEMA / Ready.gov — Extreme Cold",exp:"Hypothermia — when the body loses heat faster than it can produce it — is the most immediate life-threatening risk. Hypothermia can set in within minutes in severe cold, long before dehydration or starvation become factors."},
{id:12,cat:"shelter",q:"When sheltering in place during a chemical or radiological event, FEMA recommends sealing a room. What material should you use?",o:["Plastic sheeting and duct tape","Wet towels only","Aluminum foil and rubber bands","Heavy blankets over windows"],a:0,src:"FEMA / Ready.gov — Shelter",exp:"FEMA recommends pre-cutting plastic sheeting and using duct tape to seal windows, doors, and vents in your designated shelter room. Wet towels alone do not create an adequate seal against chemical or radiological contaminants."},
{id:13,cat:"shelter",q:"In a wilderness survival scenario, what is the primary purpose of insulation between your body and the ground?",o:["To keep insects from crawling on you","To prevent heat loss to the ground through conduction","To make the shelter more comfortable","To prevent moisture from soaking your clothes"],a:1,src:"National Park Service — Wilderness Survival Basics",exp:"Ground conduction can drain body heat up to 25 times faster than air. A common mistake is focusing only on overhead cover while ignoring ground insulation, which is the primary path of heat loss when lying down.",media:{type:"image",url:"images/shelter-debris-hut.svg",alt:"Diagram of a lean-to survival shelter showing ridge pole, supports, and debris cover",caption:"A lean-to shelter: one of the simplest emergency shelters to construct (Source: FEMA)"}},
{id:14,cat:"shelter",q:"During a tornado warning, FEMA recommends sheltering in which location?",o:["In a vehicle under an overpass for protection","In the lowest level interior room away from windows","In a garage with the door closed","Near a large window to monitor the storm"],a:1,src:"FEMA / Ready.gov — Tornadoes",exp:"FEMA recommends going to the lowest floor, in an interior room or hallway away from windows. Sheltering under an overpass is extremely dangerous — it creates a wind-tunnel effect. This is one of the most common and deadly tornado myths."},
{id:15,cat:"shelter",q:"What does the Red Cross recommend as the ideal temperature to maintain in an emergency shelter?",o:["80°F (27°C) to stay very warm","Between 64°F and 75°F (18°C–24°C)","50°F (10°C) to conserve fuel","As warm as possible regardless of temperature"],a:1,src:"American Red Cross — Heating Safety",exp:"The Red Cross recommends maintaining temperatures between 64°F and 75°F. Overheating a shelter wastes fuel and can create carbon monoxide risks; too cold risks hypothermia, especially for elderly and children."},

// ═══════════════════════════════════════════
// NAVIGATION (5 questions)
// ═══════════════════════════════════════════
{id:16,cat:"navigation",q:"When using a magnetic compass, the red end of the needle points toward what?",o:["True north (the North Pole)","Magnetic north","The nearest source of iron ore","Geographic south"],a:1,src:"NOAA / National Centers for Environmental Information — Geomagnetism FAQ",exp:"A compass needle points to magnetic north, not true north. The angular difference between magnetic north and true north is called declination, and it varies by location. Confusing the two is a common navigation error.",media:{type:"image",url:"images/navigation-compass-reading.svg",alt:"Diagram of a compass showing cardinal directions, degree markings, and the red needle pointing to magnetic north",caption:"A compass needle always points to magnetic north, not true north"}},
{id:17,cat:"navigation",q:"If you are lost in the wilderness and find a stream or river, what does the National Park Service recommend?",o:["Follow the water upstream toward higher ground","Stay put and do not follow the water at all","Follow the water downstream, as it typically leads to civilization","Cross the water immediately and continue in your original direction"],a:2,src:"National Park Service — Hiking Safety and Lost in the Wilderness",exp:"The NPS generally recommends following water downstream, as rivers and streams flow toward larger bodies of water and settlements. However, the best advice if truly lost is to stay put if rescue is expected."},
{id:18,cat:"navigation",q:"What is the 'Rule of Threes' priority order for wilderness survival?",o:["3 minutes without air, 3 hours without shelter, 3 days without water, 3 weeks without food","3 hours without water, 3 days without food, 3 weeks without shelter","3 days without air, 3 weeks without water, 3 months without food","3 minutes without food, 3 hours without water, 3 days without shelter"],a:0,src:"U.S. Forest Service — Wilderness Survival",exp:"The Rule of Threes helps prioritize survival needs: 3 minutes without air, 3 hours without shelter (in extreme conditions), 3 days without water, 3 weeks without food. Many people overestimate the urgency of food and underestimate the importance of shelter."},
{id:19,cat:"navigation",q:"In the Northern Hemisphere, which natural indicator can help you determine a general south direction during the day?",o:["Moss, which always grows on the north side of trees","The shadow cast by a vertical stick at solar noon points north","The sun, which is generally in the southern part of the sky at midday","Wind direction, which always blows from north to south"],a:2,src:"NOAA / National Weather Service — Solar Position and Navigation",exp:"In the Northern Hemisphere, the sun is generally in the southern part of the sky around midday. The moss myth is unreliable — moss grows where moisture is, not strictly on the north side. A stick shadow at noon actually points north, not south, but the sun position is the most practical indicator."},
{id:20,cat:"navigation",q:"When hiking, the standard emergency signaling technique is to use groups of how many signals (whistle blasts, mirror flashes, etc.)?",o:["Two — it stands for 'help'","Three — it is the universal distress signal","Five — it means 'emergency'","One long continuous signal"],a:1,src:"National Park Service — Hiking Safety",exp:"Three signals of any kind (three whistle blasts, three fires, three mirror flashes) is the internationally recognized distress signal. Two signals simply means 'all is well' or a response to a signal, which is a dangerous mix-up."},

// ═══════════════════════════════════════════
// EMERGENCY COMMUNICATIONS (5 questions)
// ═══════════════════════════════════════════
{id:21,cat:"comms",q:"What is the universal emergency phone number in the United States that connects to police, fire, and EMS?",o:["311","911","411","611"],a:1,src:"FCC.gov — 911 and Emergency Communications",exp:"911 is the universal emergency number in the U.S. A common point of confusion: 311 is for non-emergency municipal services, 411 is directory assistance, and 611 is a carrier-specific telecom line."},
{id:22,cat:"comms",q:"NOAA Weather Radio broadcasts on seven frequencies. What frequency range are they in?",o:["88.1–107.9 MHz (FM radio band)","162.400–162.550 MHz","530–1700 kHz (AM radio band)","462.5625–467.7125 MHz (FRS/GMRS band)"],a:1,src:"NOAA / weather.gov — NWR All Hazards",exp:"NOAA Weather Radio broadcasts on seven frequencies between 162.400 and 162.550 MHz. These require a special weather radio or scanner — they are not on standard AM/FM bands, which is a common misconception.",media:{type:"image",url:"images/comms-noaa-frequencies.svg",alt:"Diagram of a NOAA weather radio showing all seven broadcast frequencies",caption:"NOAA Weather Radio frequencies are NOT on standard AM/FM bands (Source: NOAA)"}},
{id:23,cat:"comms",q:"According to FEMA, why should your emergency communication plan include an out-of-area contact person?",o:["Local phone lines are always destroyed in disasters","Long-distance calls often get through when local calls cannot","Out-of-area contacts can send supplies faster","Cell towers only connect to numbers outside the disaster area"],a:1,src:"FEMA / Ready.gov — Make a Plan: Communication",exp:"During a disaster, local phone networks are often jammed with high call volume. Long-distance calls to an out-of-area contact frequently get through when local calls cannot. FEMA recommends designating a single out-of-area contact everyone checks in with."},
{id:24,cat:"comms",q:"What does FEMA recommend as a communication backup when cell phone networks are overloaded during a disaster?",o:["Sending email, which uses different infrastructure","Sending text messages, which use less bandwidth than voice calls","Using social media live video streaming","Making repeated calls until one gets through"],a:1,src:"FEMA / Ready.gov — Make a Plan: Communication",exp:"FEMA recommends texting during emergencies because text messages require far less bandwidth than voice calls and can often get through when calls cannot. Repeatedly calling actually worsens network congestion."},
{id:25,cat:"comms",q:"What is the Wireless Emergency Alert (WEA) system?",o:["An app you must download from FEMA's website","A free alerting system that sends emergency messages to cell phones in an affected area without requiring sign-up","A subscription-based weather notification service","An emergency radio frequency for cell phones"],a:1,src:"FCC.gov — Wireless Emergency Alerts (WEA)",exp:"WEA is a free public safety system that sends targeted emergency alerts (AMBER alerts, severe weather, presidential alerts) to all compatible cell phones in an affected area. No sign-up or app download is needed — it is built into the cellular network."},

// ═══════════════════════════════════════════
// RESCUE (5 questions)
// ═══════════════════════════════════════════
{id:26,cat:"rescue",q:"What is the internationally recognized ground-to-air signal for 'Need Assistance'?",o:["A large X made from logs or fabric","A large V made from rocks, logs, or fabric","A large circle with a dot in the center","A large triangle made from branches"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4) / Civil Air Patrol",exp:"A 'V' shape means 'Need Assistance,' while an 'X' means 'Need Medical Help.' Many people confuse the two — X is specifically for medical emergencies, not general help.",media:{type:"image",url:"images/rescue-ground-signals.svg",alt:"Diagram showing five ground-to-air emergency signals: V for assistance, X for medical, I for supplies, arrow for direction, LL for all well",caption:"Standard ground-to-air emergency signals (Source: U.S. Air Force Survival Manual)"}},
{id:27,cat:"rescue",q:"According to search and rescue experts, what is the FIRST thing you should do if you realize you are lost?",o:["Start walking downhill to find water and civilization","Stop moving, stay calm, and stay put if possible","Climb to the highest point to get cell signal","Start a large fire immediately to signal rescuers"],a:1,src:"National Park Service — If You Get Lost",exp:"The NPS and SAR teams universally recommend the STOP protocol: Stop, Think, Observe, Plan. Continuing to walk when lost is the #1 mistake — it makes you harder to find and can lead you into more danger."},
{id:28,cat:"rescue",q:"When signaling a rescue helicopter, what does waving both arms above your head in a Y-shape mean?",o:["'Land here' — indicating a safe landing zone","'Yes, I need help' — the international signal for requiring assistance","'Go away' — we do not need help","'Drop supplies' — indicating supply request"],a:1,src:"U.S. Coast Guard — Visual Distress Signals",exp:"Arms raised in a Y-shape (like the letter Y for 'Yes') signals 'Yes, I need help.' A single arm raised diagonally means 'No, do not need help.' Confusing these can cause a helicopter to pass you by."},
{id:29,cat:"rescue",q:"What is the recommended way to use a signal mirror to attract the attention of a search aircraft?",o:["Flash it rapidly in random directions to cover more sky","Aim the reflected light at the aircraft using a sighting hole or finger-aiming technique","Hold it steady above your head so it catches sunlight","Wave the mirror back and forth across the entire horizon"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4)",exp:"Signal mirrors are aimed by looking through the sighting hole (or using the V-sight between fingers) and directing the bright reflection spot onto the target aircraft. Random flashing wastes the signal and makes it unlikely to be seen."},
{id:30,cat:"rescue",q:"If trapped in a collapsed building, what does FEMA recommend you do to signal rescuers?",o:["Shout continuously at the top of your lungs to be heard","Light a match or lighter so rescuers can see the flame","Tap on a pipe or wall at regular intervals, or use a whistle","Try to dig yourself out immediately through the debris"],a:2,src:"FEMA / Ready.gov — Earthquakes",exp:"FEMA recommends tapping on pipes or walls and using a whistle rather than shouting, which can cause you to inhale dangerous dust and exhaust your energy quickly. Lighting a flame risks igniting leaking gas. Digging can destabilize debris."},

// ═══════════════════════════════════════════
// FIRST AID (5 questions)
// ═══════════════════════════════════════════
{id:31,cat:"first-aid",q:"What is the correct compression-to-breath ratio for single-rescuer adult CPR?",o:["15 compressions to 2 breaths","30 compressions to 2 breaths","20 compressions to 2 breaths","10 compressions to 1 breath"],a:1,src:"American Heart Association — CPR Guidelines 2020",exp:"The AHA recommends 30 compressions to 2 breaths for single-rescuer adult CPR. The old 15:2 ratio was changed in 2005 but remains a common incorrect answer."},
{id:32,cat:"first-aid",q:"When someone is having a severe allergic reaction (anaphylaxis), where should an epinephrine auto-injector be administered?",o:["In the upper arm (deltoid muscle)","In the outer middle thigh","In the buttocks","In the abdomen near the navel"],a:1,src:"American Red Cross — Anaphylaxis First Aid",exp:"Epinephrine auto-injectors (like EpiPen) should be injected into the outer middle thigh, which can be done through clothing. The thigh has large muscle mass and good blood supply for rapid absorption. The arm is a common wrong guess.",media:{type:"image",url:"images/first-aid-recovery-position.svg",alt:"Diagram of the recovery position showing proper body placement for an unconscious breathing person",caption:"The recovery position keeps the airway clear in an unconscious, breathing person (Source: Red Cross)"}},
{id:33,cat:"first-aid",q:"According to the Red Cross, what is the first step in caring for someone you suspect is having a stroke?",o:["Give them an aspirin immediately to thin their blood","Have them lie down and elevate their feet","Call 911 immediately — note the time symptoms started","Give them water and keep them cool"],a:2,src:"American Red Cross — Stroke First Aid / American Stroke Association",exp:"Call 911 immediately and note the exact time symptoms began — this is critical because clot-dissolving treatment (tPA) is time-sensitive. Never give aspirin — strokes can be caused by bleeding, and aspirin would make a hemorrhagic stroke worse."},
{id:34,cat:"first-aid",q:"What is the proper first aid treatment for a suspected snakebite?",o:["Cut the wound and try to suck out the venom immediately","Apply a tourniquet above the bite to stop venom from spreading","Keep the person calm, immobilize the bitten area, and get to an ER","Apply ice directly to the bite to slow the spread of venom"],a:2,src:"CDC — Venomous Snakes — First Aid",exp:"The CDC recommends keeping the person still, removing jewelry near the bite, keeping the bitten area at or below heart level, and getting to an emergency room. Cutting/sucking venom, tourniquets, and ice are all harmful myths that can worsen tissue damage."},
{id:35,cat:"first-aid",q:"During a nosebleed, what position should the person be in, and how should they hold their nose?",o:["Tilt the head back and pinch the bridge of the nose","Lean forward and pinch the soft part of the nose just below the bridge","Lie flat on their back with a cold cloth on the forehead","Tilt the head back and stuff the nostrils with cotton"],a:1,src:"American Red Cross — Nosebleed First Aid",exp:"Lean slightly forward (not back!) and pinch the soft part of the nose for at least 10 minutes. Tilting the head back — the most common mistake — causes blood to flow down the throat, which can cause nausea or choking."}
];
