const QUESTIONS = [
// ═══════════════════════════════════════════
// FOOD & NUTRITION (5 questions)
// ═══════════════════════════════════════════
{id:1,cat:"food",q:"According to FEMA, how many calories per person per day should you plan for in an emergency food supply?",o:["1,200 calories","2,000 calories","3,500 calories","800 calories"],a:1,src:"FEMA / Ready.gov — Build A Kit",exp:"Ready.gov recommends planning for approximately 2,000 calories per person per day in an emergency food supply. Many people underestimate at 1,200 or overestimate at 3,500."},
{id:2,cat:"food",q:"What is the recommended minimum emergency food supply duration according to Ready.gov?",o:["24 hours","48 hours","72 hours (3 days)","1 week (7 days) minimum"],a:2,src:"FEMA / Ready.gov — Build A Kit",exp:"Ready.gov recommends keeping at least a 72-hour (3-day) supply of non-perishable food. While longer supplies are better, 72 hours is the minimum standard."},
{id:3,cat:"food",q:"Which of these foods does the Red Cross recommend AVOIDING in an emergency kit?",o:["Canned tuna and crackers stored in a cool place","Peanut butter and jelly in sealed containers","Foods that require refrigeration after opening","Granola bars and dried fruit in original packaging"],a:2,src:"American Red Cross — Survival Kit Supplies",exp:"The Red Cross advises against including foods that require refrigeration after opening, since power outages are common during emergencies. This is a common oversight when building kits."},
{id:4,cat:"food",q:"After a power outage, how long will food in a full freezer stay safe if the door is kept closed?",o:["About 6 hours","About 48 hours","About 12 hours","About 1 week"],a:1,src:"USDA / FoodSafety.gov — Food Safety During Power Outages",exp:"A full freezer will keep food safe for approximately 48 hours (24 hours if half full) as long as the door remains closed. Many people open the door to check, which reduces this time significantly."},
{id:5,cat:"food",q:"What does the USDA recommend as the safe minimum internal temperature for all reheated leftovers?",o:["140°F (60°C)","165°F (74°C)","120°F (49°C)","200°F (93°C)"],a:1,src:"USDA / FoodSafety.gov — Safe Minimum Cooking Temperatures",exp:"The USDA recommends reheating all leftovers to 165°F (74°C). The common mistake is 140°F, which is the safe holding temperature, not the reheating temperature.",media:{type:"image",url:"images/food-emergency-kit.svg",alt:"Diagram of recommended 72-hour emergency food supply items",caption:"A well-stocked 72-hour emergency food kit includes non-perishable, high-calorie items (Source: FEMA / Ready.gov)"}},

// ═══════════════════════════════════════════
// WATER (5 questions)
// ═══════════════════════════════════════════
{id:6,cat:"water",q:"How much water per person per day does Ready.gov recommend storing for emergencies?",o:["Half a gallon","One gallon","Two gallons","Three gallons"],a:1,src:"FEMA / Ready.gov — Water",exp:"Ready.gov recommends one gallon of water per person per day for drinking and sanitation. Children, nursing mothers, and sick people may need more. A common error is thinking half a gallon is sufficient."},
{id:7,cat:"water",q:"According to the CDC, how long should you boil water to purify it at elevations below 6,500 feet?",o:["5 minutes at a full boil","1 minute at a rolling boil","10 minutes at a simmer","30 seconds at a rolling boil"],a:1,src:"CDC — Making Water Safe in an Emergency",exp:"The CDC recommends bringing water to a rolling boil for 1 minute at elevations below 6,500 feet (3 minutes above that). The old belief that you need to boil for 5-10 minutes is a common misconception — 1 minute of rolling boil kills pathogens effectively.",media:{type:"image",url:"images/water-purification-methods.svg",alt:"Diagram showing water purification by boiling with step-by-step instructions",caption:"Boiling is the most reliable method to make water safe (Source: CDC)"}},
{id:8,cat:"water",q:"If you cannot boil water, what does the EPA recommend as an alternative disinfection method?",o:["Adding 1 cup of vinegar per gallon and letting it sit for 30 minutes","Adding 8 drops (⅛ teaspoon) of unscented household bleach per gallon","Adding a tablespoon of hydrogen peroxide per gallon and stirring thoroughly","Adding a tablespoon of rubbing alcohol per gallon and letting it settle"],a:1,src:"EPA — Emergency Disinfection of Drinking Water",exp:"The EPA recommends adding 8 drops (about ⅛ teaspoon) of regular unscented liquid household bleach per gallon of clear water. Vinegar, hydrogen peroxide, and rubbing alcohol are not effective alternatives."},
{id:9,cat:"water",q:"According to Ready.gov, how long can commercially bottled water be safely stored if kept in proper conditions?",o:["6 months maximum before quality degrades significantly","Indefinitely if unopened and properly stored","1 year at most before it becomes unsafe to drink","2 years at most according to FDA guidelines"],a:1,src:"FEMA / Ready.gov — Water",exp:"Ready.gov states that commercially bottled water can be stored indefinitely if kept unopened in a cool, dark place. The expiration dates on bottles are for quality, not safety. Many people discard perfectly safe water based on expiration dates."},
{id:10,cat:"water",q:"What is the primary danger of drinking untreated water from streams or lakes during an emergency?",o:["Heavy metal poisoning from mineral deposits in the streambed","Waterborne pathogens like Giardia, Cryptosporidium, and bacteria","Chemical contamination from dissolved oxygen and natural minerals","Excessive mineral content causing kidney stones and organ damage"],a:1,src:"CDC — Wilderness Water Disinfection",exp:"The primary danger is waterborne pathogens including parasites (Giardia, Cryptosporidium), bacteria (E. coli, Salmonella), and viruses. Even clear-looking water can harbor these organisms."},

// ═══════════════════════════════════════════
// SHELTER (5 questions)
// ═══════════════════════════════════════════
{id:11,cat:"shelter",q:"According to FEMA, what is the most immediate threat to survival in a cold-weather emergency without shelter?",o:["Dehydration from dry cold air","Hypothermia from exposure","Frostbite on extremities","Starvation from increased calorie burn"],a:1,src:"FEMA / Ready.gov — Extreme Cold",exp:"Hypothermia — when the body loses heat faster than it can produce it — is the most immediate life-threatening risk. Hypothermia can set in within minutes in severe cold, long before dehydration or starvation become factors."},
{id:12,cat:"shelter",q:"When sheltering in place during a chemical or radiological event, FEMA recommends sealing a room. What material should you use?",o:["Plastic sheeting and duct tape","Wet towels only","Aluminum foil and rubber bands","Heavy blankets over windows"],a:0,src:"FEMA / Ready.gov — Shelter",exp:"FEMA recommends pre-cutting plastic sheeting and using duct tape to seal windows, doors, and vents in your designated shelter room. Wet towels alone do not create an adequate seal against chemical or radiological contaminants."},
{id:13,cat:"shelter",q:"In a wilderness survival scenario, what is the primary purpose of insulation between your body and the ground?",o:["To keep insects and small crawling animals from reaching you","To prevent heat loss to the ground through conduction","To make the shelter more comfortable for resting and sleeping","To prevent moisture from soaking your clothes and gear"],a:1,src:"National Park Service — Wilderness Survival Basics",exp:"Ground conduction can drain body heat up to 25 times faster than air. A common mistake is focusing only on overhead cover while ignoring ground insulation, which is the primary path of heat loss when lying down.",media:{type:"image",url:"images/shelter-debris-hut.svg",alt:"Diagram of a lean-to survival shelter showing ridge pole, supports, and debris cover",caption:"A lean-to shelter: one of the simplest emergency shelters to construct (Source: FEMA)"}},
{id:14,cat:"shelter",q:"During a tornado warning, FEMA recommends sheltering in which location?",o:["In a vehicle under an overpass for overhead protection from debris","In the lowest level interior room away from windows","In a garage with the door closed for reinforced shelter","Near a large window to monitor the approaching storm"],a:1,src:"FEMA / Ready.gov — Tornadoes",exp:"FEMA recommends going to the lowest floor, in an interior room or hallway away from windows. Sheltering under an overpass is extremely dangerous — it creates a wind-tunnel effect. This is one of the most common and deadly tornado myths."},
{id:15,cat:"shelter",q:"What does the Red Cross recommend as the ideal temperature to maintain in an emergency shelter?",o:["80°F (27°C) to stay very warm","Between 64°F and 75°F (18°C–24°C)","50°F (10°C) to conserve fuel","As warm as possible regardless of temperature"],a:1,src:"American Red Cross — Heating Safety",exp:"The Red Cross recommends maintaining temperatures between 64°F and 75°F. Overheating a shelter wastes fuel and can create carbon monoxide risks; too cold risks hypothermia, especially for elderly and children."},

// ═══════════════════════════════════════════
// NAVIGATION (5 questions)
// ═══════════════════════════════════════════
{id:16,cat:"navigation",q:"When using a magnetic compass, the red end of the needle points toward what?",o:["True north (the North Pole)","Magnetic north","The nearest source of iron ore","Geographic south"],a:1,src:"NOAA / National Centers for Environmental Information — Geomagnetism FAQ",exp:"A compass needle points to magnetic north, not true north. The angular difference between magnetic north and true north is called declination, and it varies by location. Confusing the two is a common navigation error.",media:{type:"image",url:"images/navigation-compass-reading.svg",alt:"Diagram of a compass showing cardinal directions, degree markings, and the red needle pointing to magnetic north",caption:"A compass needle always points to magnetic north, not true north"}},
{id:17,cat:"navigation",q:"If you are lost in the wilderness and find a stream or river, what does the National Park Service recommend?",o:["Follow the water upstream toward higher ground","Stay put and do not follow the water at all","Follow the water downstream, as it typically leads to civilization","Cross the water immediately and continue in your original direction"],a:2,src:"National Park Service — Hiking Safety and Lost in the Wilderness",exp:"The NPS generally recommends following water downstream, as rivers and streams flow toward larger bodies of water and settlements. However, the best advice if truly lost is to stay put if rescue is expected."},
{id:18,cat:"navigation",q:"What is the 'Rule of Threes' priority order for wilderness survival?",o:["3 minutes without air, 3 hours without shelter, 3 days without water, 3 weeks without food","3 hours without water, 3 days without food, 3 weeks without shelter in harsh conditions","3 days without air, 3 weeks without water, 3 months without food in temperate climate zones","3 minutes without food, 3 hours without water, 3 days without shelter in cold weather zones"],a:0,src:"U.S. Forest Service — Wilderness Survival",exp:"The Rule of Threes helps prioritize survival needs: 3 minutes without air, 3 hours without shelter (in extreme conditions), 3 days without water, 3 weeks without food. Many people overestimate the urgency of food and underestimate the importance of shelter."},
{id:19,cat:"navigation",q:"In the Northern Hemisphere, which natural indicator can help you determine a general south direction during the day?",o:["Moss, which always grows on the north side of trees in all climates","The shadow cast by a vertical stick at solar noon, which points north","The sun, which is generally in the southern part of the sky at midday","Wind direction, which always blows from north to south in open terrain"],a:2,src:"NOAA / National Weather Service — Solar Position and Navigation",exp:"In the Northern Hemisphere, the sun is generally in the southern part of the sky around midday. The moss myth is unreliable — moss grows where moisture is, not strictly on the north side. A stick shadow at noon actually points north, not south, but the sun position is the most practical indicator."},
{id:20,cat:"navigation",q:"When hiking, the standard emergency signaling technique is to use groups of how many signals (whistle blasts, mirror flashes, etc.)?",o:["Two — it stands for 'help' in international signaling","Three — it is the universal distress signal","Five — it means 'emergency' in wilderness protocol","One long continuous signal repeated at intervals"],a:1,src:"National Park Service — Hiking Safety",exp:"Three signals of any kind (three whistle blasts, three fires, three mirror flashes) is the internationally recognized distress signal. Two signals simply means 'all is well' or a response to a signal, which is a dangerous mix-up."},

// ═══════════════════════════════════════════
// EMERGENCY COMMUNICATIONS (5 questions)
// ═══════════════════════════════════════════
{id:21,cat:"comms",q:"What is the universal emergency phone number in the United States that connects to police, fire, and EMS?",o:["311","911","411","611"],a:1,src:"FCC.gov — 911 and Emergency Communications",exp:"911 is the universal emergency number in the U.S. A common point of confusion: 311 is for non-emergency municipal services, 411 is directory assistance, and 611 is a carrier-specific telecom line."},
{id:22,cat:"comms",q:"NOAA Weather Radio broadcasts on seven frequencies. What frequency range are they in?",o:["88.1–107.9 MHz (FM radio band)","162.400–162.550 MHz","530–1700 kHz (AM radio band)","462.5625–467.7125 MHz (FRS/GMRS band)"],a:1,src:"NOAA / weather.gov — NWR All Hazards",exp:"NOAA Weather Radio broadcasts on seven frequencies between 162.400 and 162.550 MHz. These require a special weather radio or scanner — they are not on standard AM/FM bands, which is a common misconception.",media:{type:"image",url:"images/comms-noaa-frequencies.svg",alt:"Diagram of a NOAA weather radio showing all seven broadcast frequencies",caption:"NOAA Weather Radio frequencies are NOT on standard AM/FM bands (Source: NOAA)"}},
{id:23,cat:"comms",q:"According to FEMA, why should your emergency communication plan include an out-of-area contact person?",o:["Local phone lines are always destroyed in disasters","Long-distance calls often get through when local calls cannot","Out-of-area contacts can send supplies faster","Cell towers only connect to numbers outside the disaster area"],a:1,src:"FEMA / Ready.gov — Make a Plan: Communication",exp:"During a disaster, local phone networks are often jammed with high call volume. Long-distance calls to an out-of-area contact frequently get through when local calls cannot. FEMA recommends designating a single out-of-area contact everyone checks in with."},
{id:24,cat:"comms",q:"What does FEMA recommend as a communication backup when cell phone networks are overloaded during a disaster?",o:["Sending email, which uses completely different network infrastructure","Sending text messages, which use less bandwidth than voice calls","Using social media live video streaming to reach emergency services","Making repeated calls until one gets through to the dispatcher"],a:1,src:"FEMA / Ready.gov — Make a Plan: Communication",exp:"FEMA recommends texting during emergencies because text messages require far less bandwidth than voice calls and can often get through when calls cannot. Repeatedly calling actually worsens network congestion."},
{id:25,cat:"comms",q:"What is the Wireless Emergency Alert (WEA) system?",o:["An app you must download from FEMA's website and register with your local emergency management office before alerts work","A free alerting system that sends emergency messages to cell phones in an affected area without requiring sign-up","A subscription-based weather notification service that charges a monthly fee for premium real-time emergency alert access","An emergency radio frequency built into cell phones that requires manual activation in your device's settings menu"],a:1,src:"FCC.gov — Wireless Emergency Alerts (WEA)",exp:"WEA is a free public safety system that sends targeted emergency alerts (AMBER alerts, severe weather, presidential alerts) to all compatible cell phones in an affected area. No sign-up or app download is needed — it is built into the cellular network."},

// ═══════════════════════════════════════════
// RESCUE (5 questions)
// ═══════════════════════════════════════════
{id:26,cat:"rescue",q:"What is the internationally recognized ground-to-air signal for 'Need Assistance'?",o:["A large X made from logs or fabric on open ground","A large V made from rocks, logs, or fabric","A large circle with a dot in the center of it","A large triangle made from branches or stones"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4) / Civil Air Patrol",exp:"A 'V' shape means 'Need Assistance,' while an 'X' means 'Need Medical Help.' Many people confuse the two — X is specifically for medical emergencies, not general help.",media:{type:"image",url:"images/rescue-ground-signals.svg",alt:"Diagram showing five ground-to-air emergency signals: V for assistance, X for medical, I for supplies, arrow for direction, LL for all well",caption:"Standard ground-to-air emergency signals (Source: U.S. Air Force Survival Manual)"}},
{id:27,cat:"rescue",q:"According to search and rescue experts, what is the FIRST thing you should do if you realize you are lost?",o:["Start walking downhill to find water and civilization","Stop moving, stay calm, and stay put if possible","Climb to the highest point to get cell signal","Start a large fire immediately to signal rescuers"],a:1,src:"National Park Service — If You Get Lost",exp:"The NPS and SAR teams universally recommend the STOP protocol: Stop, Think, Observe, Plan. Continuing to walk when lost is the #1 mistake — it makes you harder to find and can lead you into more danger."},
{id:28,cat:"rescue",q:"When signaling a rescue helicopter, what does waving both arms above your head in a Y-shape mean?",o:["'Land here' — indicating a safe and clear landing zone for the aircraft","'Yes, I need help' — the international signal for requiring assistance","'Go away' — we do not need help at this location","'Drop supplies' — indicating a supply request without landing"],a:1,src:"U.S. Coast Guard — Visual Distress Signals",exp:"Arms raised in a Y-shape (like the letter Y for 'Yes') signals 'Yes, I need help.' A single arm raised diagonally means 'No, do not need help.' Confusing these can cause a helicopter to pass you by."},
{id:29,cat:"rescue",q:"What is the recommended way to use a signal mirror to attract the attention of a search aircraft?",o:["Flash it rapidly in random directions to cover as much sky as possible for passing aircraft","Aim the reflected light at the aircraft using a sighting hole or finger-aiming technique","Hold it steady above your head so it catches sunlight and creates a continuous visible flash","Wave the mirror back and forth in a sweeping arc across the entire horizon line repeatedly"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4)",exp:"Signal mirrors are aimed by looking through the sighting hole (or using the V-sight between fingers) and directing the bright reflection spot onto the target aircraft. Random flashing wastes the signal and makes it unlikely to be seen."},
{id:30,cat:"rescue",q:"If trapped in a collapsed building, what does FEMA recommend you do to signal rescuers?",o:["Shout continuously at the top of your lungs to be heard by rescuers","Light a match or lighter so rescuers can see the flame in the dark","Tap on a pipe or wall at regular intervals, or use a whistle","Try to dig yourself out immediately through the surrounding debris"],a:2,src:"FEMA / Ready.gov — Earthquakes",exp:"FEMA recommends tapping on pipes or walls and using a whistle rather than shouting, which can cause you to inhale dangerous dust and exhaust your energy quickly. Lighting a flame risks igniting leaking gas. Digging can destabilize debris."},

// ═══════════════════════════════════════════
// FIRST AID (5 questions)
// ═══════════════════════════════════════════
{id:31,cat:"first-aid",q:"What is the correct compression-to-breath ratio for single-rescuer adult CPR?",o:["15 compressions to 2 breaths","30 compressions to 2 breaths","20 compressions to 2 breaths","10 compressions to 1 breath"],a:1,src:"American Heart Association — CPR Guidelines 2020",exp:"The AHA recommends 30 compressions to 2 breaths for single-rescuer adult CPR. The old 15:2 ratio was changed in 2005 but remains a common incorrect answer."},
{id:32,cat:"first-aid",q:"When someone is having a severe allergic reaction (anaphylaxis), where should an epinephrine auto-injector be administered?",o:["In the upper arm (deltoid muscle)","In the outer middle thigh","In the buttocks","In the abdomen near the navel"],a:1,src:"American Red Cross — Anaphylaxis First Aid",exp:"Epinephrine auto-injectors (like EpiPen) should be injected into the outer middle thigh, which can be done through clothing. The thigh has large muscle mass and good blood supply for rapid absorption. The arm is a common wrong guess.",media:{type:"image",url:"images/first-aid-recovery-position.svg",alt:"Diagram of the recovery position showing proper body placement for an unconscious breathing person",caption:"The recovery position keeps the airway clear in an unconscious, breathing person (Source: Red Cross)"}},
{id:33,cat:"first-aid",q:"According to the Red Cross, what is the first step in caring for someone you suspect is having a stroke?",o:["Give them an aspirin immediately to thin their blood and restore flow","Have them lie down and elevate their feet above heart level","Call 911 immediately — note the time symptoms started","Give them water and keep them cool until help arrives"],a:2,src:"American Red Cross — Stroke First Aid / American Stroke Association",exp:"Call 911 immediately and note the exact time symptoms began — this is critical because clot-dissolving treatment (tPA) is time-sensitive. Never give aspirin — strokes can be caused by bleeding, and aspirin would make a hemorrhagic stroke worse."},
{id:34,cat:"first-aid",q:"What is the proper first aid treatment for a suspected snakebite?",o:["Cut the wound and try to suck out the venom immediately before it spreads","Apply a tourniquet tightly above the bite to stop venom from spreading further","Keep the person calm, immobilize the bitten area, and get to an ER","Apply ice directly to the bite to reduce swelling and slow the spread of venom"],a:2,src:"CDC — Venomous Snakes — First Aid",exp:"The CDC recommends keeping the person still, removing jewelry near the bite, keeping the bitten area at or below heart level, and getting to an emergency room. Cutting/sucking venom, tourniquets, and ice are all harmful myths that can worsen tissue damage."},
{id:35,cat:"first-aid",q:"During a nosebleed, what position should the person be in, and how should they hold their nose?",o:["Tilt the head back and pinch the bridge of the nose firmly for ten minutes","Lean forward and pinch the soft part of the nose just below the bridge","Lie flat on their back with a cold damp cloth placed on the forehead","Tilt the head back and stuff the nostrils tightly with cotton or gauze"],a:1,src:"American Red Cross — Nosebleed First Aid",exp:"Lean slightly forward (not back!) and pinch the soft part of the nose for at least 10 minutes. Tilting the head back — the most common mistake — causes blood to flow down the throat, which can cause nausea or choking."},

// ═══════════════════════════════════════════
// SURVIVAL PSYCHOLOGY & DECISION MAKING (5)
// ═══════════════════════════════════════════
{id:36,cat:"psychology",q:"What does the survival acronym STOP stand for, used to prevent panic when you realize you're in an emergency?",o:["Signal, Think, Observe, Protect","Stop, Think, Observe, Plan","Stay, Talk, Orient, Proceed","Shelter, Triage, Organize, Prioritize"],a:1,src:"U.S. Forest Service — Wilderness Survival",exp:"STOP stands for Stop, Think, Observe, Plan. The most critical step is the first one — stopping. Panic-driven movement is the leading cause of worsening an already bad situation."},
{id:37,cat:"psychology",q:"According to survival psychology research, what is the single most dangerous emotional response in a survival situation?",o:["Anger, which causes reckless and impulsive decisions under pressure","Denial — refusing to accept the reality of the situation","Sadness, which leads to giving up and withdrawing from action","Fear, which causes complete paralysis and inability to respond"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4) — Psychology of Survival",exp:"Denial is the most dangerous response because it delays action during the critical early hours. People in denial waste time expecting rescue, waiting for normalcy to return, or refusing to believe the severity of the situation. Fear and anger are unpleasant but tend to drive action."},
{id:38,cat:"psychology",q:"When responsible for children during an emergency, what does FEMA recommend as the most important psychological action?",o:["Shield them from all information about the emergency to prevent any panic","Project calm and give them age-appropriate information and simple tasks","Tell them everything will be fine and not to worry about the situations","Keep them physically active to distract them from fear and any uncertainty"],a:1,src:"FEMA / Ready.gov — Helping Children Cope",exp:"FEMA recommends honest, age-appropriate communication and giving children simple tasks (hold the flashlight, carry the water bottle). This gives them a sense of control. Shielding them entirely increases anxiety because children sense when adults are scared."},
{id:39,cat:"psychology",q:"In group survival situations, what leadership approach does the U.S. military teach for making decisions under extreme stress?",o:["The most physically strong person should lead all decisions and direct the group's activities","Democratic vote on every decision to maintain group morale and ensure fairness among all members","A clear leader should make rapid decisions, delegate tasks, and communicate the plan simply","Decisions should be avoided until the group has full information about the situation and options"],a:2,src:"U.S. Army Field Manual FM 6-22 — Leader Development",exp:"Clear, decisive leadership with simple communication is critical under stress. Democratic deliberation wastes time in emergencies. Waiting for full information is a luxury survival situations don't afford. The leader doesn't need to be the strongest — they need to think clearly and communicate."},
{id:40,cat:"psychology",q:"What is 'normalcy bias' and why is it dangerous in emergencies?",o:["The tendency to help strangers before your own family during a crisis situation","The belief that because something has never happened before, it won't happen now","The tendency to overreact to minor threats and ignore larger actual dangers","The belief that emergency supplies are unnecessary in modern society with technology"],a:1,src:"FEMA — National Household Survey on Disaster Preparedness",exp:"Normalcy bias causes people to underestimate the probability and impact of a disaster. Studies show up to 70% of people in emergencies initially do nothing, waiting for the situation to 'return to normal.' This delay can be fatal in fast-moving events like fires, floods, or building collapses."},

// ═══════════════════════════════════════════
// FIRE, CLOTHING & EQUIPMENT (5)
// ═══════════════════════════════════════════
{id:41,cat:"fire-clothing",q:"What is the most important principle of dressing for cold-weather survival?",o:["Wear the thickest single layer you can find","Dress in multiple loose layers that trap air between them","Wear tight-fitting clothing to keep heat close to the body","Prioritize waterproof outer layers over everything else"],a:1,src:"American Red Cross — Winter Safety; U.S. Army FM 21-76 Survival Manual",exp:"Layering traps insulating air between garments and allows you to adjust for activity level (preventing sweat). The three layers are: wicking base layer, insulating middle layer, and wind/waterproof outer layer. A single thick layer provides less insulation and causes overheating during exertion."},
{id:42,cat:"fire-clothing",q:"In a survival situation, why is wet clothing so dangerous in cold weather?",o:["Wet clothing attracts predators due to the stronger scent it produces in cold environments","Wet fabric restricts blood circulation and increases the risk of dangerous clotting","Water conducts heat away from the body up to 25 times faster than dry air","Wet clothing causes skin infections and dangerous rashes within just a few hours"],a:2,src:"CDC — Hypothermia Prevention; U.S. Army FM 21-76 Survival Manual",exp:"Water is an extremely efficient thermal conductor — it pulls heat from the body approximately 25 times faster than dry air at the same temperature. This is why the survival saying 'cotton kills' exists: cotton absorbs water, loses all insulating value, and accelerates hypothermia."},
{id:43,cat:"fire-clothing",q:"What are the three elements required to start and maintain a fire, known as the 'fire triangle'?",o:["Wood, matches, and wind","Heat, fuel, and oxygen","Spark, tinder, and kindling","Friction, dryness, and fuel"],a:1,src:"FEMA / U.S. Fire Administration — Fire Safety",exp:"The fire triangle requires heat (ignition source), fuel (combustible material), and oxygen. Remove any one element and the fire goes out. Understanding this helps both in starting fires for survival and extinguishing unwanted fires."},
{id:44,cat:"fire-clothing",q:"When building a survival fire, what is the correct sequence of fuel sizes?",o:["Start with large logs, then add smaller pieces once it's burning","Start with tinder, then kindling, then progressively larger fuel","Start with kindling, skip tinder, and go straight to fuel wood","Use only one size of fuel for a consistent burn"],a:1,src:"U.S. Army FM 21-76 Survival Manual — Fire Building",exp:"The correct progression is: tinder (fine, easily ignitable material like dry grass or bark shavings), then kindling (pencil-sized sticks), then fuel (wrist-sized and larger). Each stage generates enough heat to ignite the next size up. Skipping stages is the most common fire-building failure."},
{id:45,cat:"fire-clothing",q:"A plastic water bottle can be repurposed in a survival situation to do what?",o:["Start a fire by focusing sunlight through the water as a magnifying lens","Filter bacteria and sediment out of contaminated water for safe drinking","Insulate your feet inside your boots to prevent frostbite in cold weather","Create a waterproof bandage or wound covering for injuries in the field"],a:0,src:"U.S. Air Force Survival Manual (AF 64-4) — Improvised Tools",exp:"A clear plastic bottle filled with water can focus sunlight to a point hot enough to ignite tinder, functioning like a magnifying glass. This is a proven survival technique when no other ignition source is available. It requires clear water, a round bottle, and direct sunlight."},

// ═══════════════════════════════════════════
// PLANNING & PREPARATION (5)
// ═══════════════════════════════════════════
{id:46,cat:"planning",q:"According to FEMA, what is the minimum recommended duration for a household emergency supply kit?",o:["24 hours","48 hours","72 hours (3 days)","2 weeks (14 days)"],a:2,src:"FEMA / Ready.gov — Build A Kit",exp:"FEMA recommends at minimum a 72-hour supply of food, water, and essential supplies per person. However, after recent disasters (Hurricane Katrina, Hurricane Maria), many emergency management experts now recommend two weeks of supplies as a more realistic target."},
{id:47,cat:"planning",q:"What critical information does FEMA recommend you include in a written family emergency communication plan?",o:["A list of all household valuables and their estimated replacement cost for insurance purposes only","An out-of-area emergency contact, meeting places, and each family member's medical information","The location of the nearest military base and government-run emergency coordination center","Your home insurance policy number, agent contact information, and full coverage documentation"],a:1,src:"FEMA / Ready.gov — Make a Plan",exp:"A family communication plan should include: an out-of-area contact person (local lines jam, long-distance often works), two meeting locations (one near home, one outside the neighborhood), important medical information, and copies of key documents. Insurance details matter but aren't the priority for a survival communication plan."},
{id:48,cat:"planning",q:"Before going on a wilderness trip, the National Park Service recommends leaving what with a trusted person?",o:["Your last will and testament along with power of attorney documentation and beneficiary designations for all accounts","A detailed trip plan including route, expected return time, vehicle description, and emergency contacts","A complete list of your gear with photos and estimated replacement values for insurance claims in case of loss or damage","Your phone's GPS tracking password, login credentials for location sharing services, and your carrier account information"],a:1,src:"National Park Service — Plan and Prepare for Your Visit",exp:"A trip plan is your lifeline if something goes wrong. It tells rescuers exactly where to start looking, what vehicle to locate at the trailhead, and when to trigger a search. Without one, SAR teams are searching blind — which is what happened in Scenario 1."},
{id:49,cat:"planning",q:"What does the emergency management principle of 'all-hazards planning' mean?",o:["Planning only for the most likely disaster in your specific geographic region and climate zone","Preparing a single flexible plan that addresses common needs across all types of emergencies","Planning separately for every possible type of disaster with individual dedicated supply kits","Focusing exclusively on natural disasters, not man-made ones like industrial or terrorism events"],a:1,src:"FEMA — National Preparedness Goal / Ready.gov",exp:"All-hazards planning recognizes that most emergencies share common needs: shelter, water, food, communication, and first aid. Rather than creating separate plans for earthquakes, hurricanes, and pandemics, one flexible plan covers the fundamentals that apply to all scenarios. This prevents the paralysis of trying to prepare for everything individually."},
{id:50,cat:"planning",q:"According to Ready.gov, how often should you review and update your household emergency plan and supplies?",o:["Every 5 years or after a major life change","Only after experiencing an actual emergency","At least once a year","Every month"],a:2,src:"FEMA / Ready.gov — Make a Plan",exp:"FEMA recommends reviewing your plan at least annually — updating contact numbers, checking expiration dates on food and water, replacing batteries, updating medical information, and practicing the plan with your household. Many people create a plan and never revisit it."},

// ═══════════════════════════════════════════
// ENVIRONMENTAL HAZARDS & PPE (5)
// ═══════════════════════════════════════════
{id:51,cat:"hazards-ppe",q:"When working near debris after a disaster, what type of respiratory protection does OSHA recommend to guard against dust, mold, and particulates?",o:["A bandana or cloth tied over the nose and mouth to block large dust particles","An N95 particulate respirator that forms a tight seal around the nose and mouth","A standard surgical mask worn loosely over the nose and mouth area","No protection is needed if you can't smell anything harmful in the surrounding air"],a:1,src:"OSHA — Respiratory Protection for Disaster Cleanup; CDC/NIOSH — Respirator Selection Guide",exp:"OSHA recommends at minimum an N95 particulate respirator for disaster cleanup work. Debris, mold spores, and fine dust from collapsed structures can cause serious lung damage. A bandana filters very little. Surgical masks don't seal. Many harmful particles are too small to smell, so the absence of odor doesn't mean the air is safe."},
{id:52,cat:"hazards-ppe",q:"If you need to improvise a face covering to protect against dust, smoke, or debris and have no mask, what does FEMA recommend?",o:["Breathe through your sleeve or a tightly woven cotton cloth dampened with water","Hold your breath and move as quickly as possible through the hazard area to reach clean air","Wrap plastic wrap loosely around your face to create a sealed protective barrier","Stuff tissue paper or cotton into your nostrils to filter out harmful particles"],a:0,src:"FEMA / Ready.gov — Explosions; CDC — Emergency Preparedness: Respiratory Protection",exp:"A damp tightly-woven cloth over the nose and mouth filters larger particles (dust, ash, debris). It is NOT effective against chemical or biological agents, but in a debris/dust emergency it's better than nothing. The moisture helps trap particles."},
{id:53,cat:"hazards-ppe",q:"What is the primary danger of carbon monoxide (CO), and why is it called 'the silent killer'?",o:["It causes severe chemical skin burns on contact with open air and any exposed skin surfaces","It is colorless and odorless, so victims don't realize they're being poisoned until symptoms are severe","It only affects people who are sleeping or unconscious, making nighttime exposure the primary risk factor","It makes buildings structurally unstable over time by corroding metal supports and weakening concrete foundations"],a:1,src:"CDC — Carbon Monoxide Poisoning Prevention; FEMA / Ready.gov — Power Outages",exp:"CO is colorless, odorless, and tasteless — victims cannot detect it without a CO detector. It displaces oxygen in the blood, causing confusion, loss of consciousness, and death. It's a major risk during power outages when people use generators, grills, or fuel-burning heaters indoors."},
{id:54,cat:"hazards-ppe",q:"After a flood, what hidden health hazard does the CDC warn is present in all floodwater?",o:["Radiation from disturbed underground mineral sources released by floodwater erosion","Contamination with sewage, chemicals, and bacteria — assume all floodwater is toxic","Extremely low pH acid that burns skin on contact and causes chemical injuries","Parasitic insects that breed instantly in standing water and carry dangerous diseases"],a:1,src:"CDC — Flood Safety / After a Flood",exp:"The CDC warns that all floodwater should be assumed contaminated with sewage, agricultural chemicals, industrial waste, and bacteria. Even shallow floodwater can cause serious infections through cuts or ingestion. Never walk, swim, or drive through floodwater."},
{id:55,cat:"hazards-ppe",q:"According to OSHA, what does the 30/30 rule refer to for lightning safety?",o:["Stay indoors for 30 minutes after a storm passes, and never shelter under trees within 30 feet of your position during any active lightning activity in the area","If the time between a lightning flash and thunder is 30 seconds or less, seek shelter — and wait 30 minutes after the last flash before going back outside","Run 30 yards from any tall objects and crouch for 30 seconds with your feet together and head tucked down to minimize your profile as a potential lightning target","Lightning is dangerous within 30 miles and 30 minutes of any storm front, so you should seek substantial indoor shelter immediately when thunder becomes audible"],a:1,src:"OSHA — Lightning Safety; NOAA / National Weather Service — Lightning Safety",exp:"The 30/30 rule: if you count fewer than 30 seconds between a lightning flash and its thunder, you are within striking distance and should immediately seek shelter. After the last observed flash, wait 30 minutes before going back outside. Most lightning deaths occur from people returning outside too soon."},

// ═══════════════════════════════════════════
// CAMPCRAFT / LIVING OUTSIDE (5)
// ═══════════════════════════════════════════
{id:56,cat:"campcraft",q:"When selecting a campsite in the wilderness, which location should you avoid?",o:["Flat ground near a water source but elevated above it","A dry riverbed or wash — it's flat and sheltered from wind","A site with natural windbreaks like rock formations or dense trees","High ground with good visibility and drainage"],a:1,src:"National Park Service — Backcountry Camping Guidelines; U.S. Army FM 21-76 Survival Manual",exp:"Dry riverbeds (arroyos, washes) are extremely dangerous campsites because flash floods can fill them in minutes — even from storms miles away that you can't see. This is one of the most common fatal camping mistakes in the western United States."},
{id:57,cat:"campcraft",q:"What is the 'Leave No Trace' recommended distance for making camp from any water source?",o:["At least 10 feet from the nearest water source","At least 200 feet (about 70 adult steps)","At least 50 feet from the nearest water source","At least 500 feet from the nearest water source"],a:1,src:"Leave No Trace Center for Outdoor Ethics — Seven Principles",exp:"Leave No Trace guidelines recommend camping at least 200 feet (approximately 70 adult steps) from lakes and streams. This protects water quality, reduces impact on riparian zones, and reduces encounter risk with wildlife that uses water sources, especially at dawn and dusk."},
{id:58,cat:"campcraft",q:"What is the safest way to purify water for drinking if you have no filter, chemicals, or ability to boil?",o:["Let it settle in a clear container for 24 hours so that particles and sediment drop to the bottom naturally","Use the SODIS method — fill a clear plastic bottle and place it in direct sunlight for at least 6 hours","Strain it through a cloth and drink it — fabric removes pathogens and makes the water safe for consumption","Add a handful of dirt to absorb contaminants and bacteria, then strain the water through fabric before drinking"],a:1,src:"WHO — Solar Water Disinfection (SODIS); CDC — Making Water Safe",exp:"SODIS (Solar Water Disinfection) uses UV radiation from sunlight to kill pathogens. Fill a clear PET bottle with relatively clear water and expose to direct sunlight for at least 6 hours (2 days if cloudy). It's endorsed by the WHO as an effective emergency method when no other option exists."},
{id:59,cat:"campcraft",q:"How should food be stored at a wilderness campsite to prevent bear and animal encounters?",o:["In your tent so you can monitor it overnight and keep it safe from any wildlife or animals that might approach your campsite area","In a bear canister or hung from a tree at least 10 feet high, 4 feet from the trunk, and 200 feet from your sleeping area","Buried in a hole near your campsite at a depth of at least two feet to fully mask the scent from any nearby foraging wildlife","Spread out on the ground around the full perimeter of camp to reduce the concentrated scent that would attract animals to one spot"],a:1,src:"National Park Service — Bear Safety and Food Storage",exp:"The NPS requires proper food storage in bear country: bear canisters or the PCT method (hung 10 feet high, 4 feet from trunk, 200+ feet from camp). Keeping food in your tent is the most dangerous option — it attracts bears directly to sleeping humans."},
{id:60,cat:"campcraft",q:"What is the most reliable natural indicator that you are near a water source in the wilderness?",o:["Large predator tracks — they always establish territories near water sources","Converging animal trails and increasing density of green vegetation","Flat, open terrain with no trees or ground cover visible","Areas with heavy spider web activity concentrated in one location"],a:1,src:"U.S. Army FM 21-76 Survival Manual — Water Procurement",exp:"Converging animal trails and lush green vegetation (especially in otherwise dry terrain) are reliable indicators of nearby water. Animals need water daily and create trails to sources. Increasing vegetation density indicates higher water table. Follow trails downhill where they converge."},

// ═══════════════════════════════════════════
// SURVIVAL PRIORITIES (5)
// ═══════════════════════════════════════════
{id:61,cat:"priorities",q:"According to the 'Rule of Threes,' which survival need is most urgent?",o:["Water — you can only survive 3 days without it at most","Shelter — you can die of exposure in as little as 3 hours","Air/breathing — you can only survive 3 minutes without it","Food — your body needs fuel within 3 hours of heavy exertion"],a:2,src:"U.S. Forest Service — Wilderness Survival; U.S. Air Force Survival Manual (AF 64-4)",exp:"The Rule of Threes prioritizes: 3 minutes without air, 3 hours without shelter (in extreme conditions), 3 days without water, 3 weeks without food. Air is always first — clear the airway, escape smoke or water, ensure breathing before anything else."},
{id:62,cat:"priorities",q:"In a disaster with multiple injured people and limited resources, what system do emergency responders use to decide who to help first?",o:["First come, first served — help people in the order you find them at the scene","Triage — prioritize based on severity of injuries and likelihood of survival","Help the most severely injured person first regardless of their survival odds","Help children and elderly first, then treat adults based on injury severity"],a:1,src:"FEMA — Community Emergency Response Team (CERT) Basic Training Manual, Unit 3: Triage",exp:"Triage (from the French 'to sort') categorizes patients into groups: immediate (life-threatening but survivable with intervention), delayed (serious but can wait), minor (walking wounded), and expectant (unlikely to survive). It ensures the most lives are saved with limited resources, rather than spending all resources on one person."},
{id:63,cat:"priorities",q:"If you are in a vehicle during a flash flood and water starts rising around you, what is the correct action according to the National Weather Service?",o:["Stay in the vehicle — it's the safest shelter from rushing water","Drive through the water quickly before it rises any higher around you","Abandon the vehicle immediately and move to higher ground","Open the windows to equalize water pressure inside the vehicle"],a:2,src:"NOAA / National Weather Service — Turn Around Don't Drown; Ready.gov — Floods",exp:"'Turn Around Don't Drown' — if water is rising around your vehicle, abandon it and move to higher ground immediately. Just 2 feet of moving water can float a vehicle, and 6 inches of fast-moving water can knock an adult off their feet. More people die in vehicles during flash floods than anywhere else."},
{id:64,cat:"priorities",q:"During an earthquake, what does FEMA recommend you do if you are indoors?",o:["Run outside immediately to open ground away from all structures and overhead hazards","Stand in a doorway — it's the strongest part of the structure","Drop, Cover, and Hold On — get under sturdy furniture and protect your head","Lie flat on the floor in the center of the room away from any furniture"],a:2,src:"FEMA / Ready.gov — Earthquakes; CDC — Earthquake Safety",exp:"Drop, Cover, and Hold On is the proven protocol: drop to hands and knees, take cover under a sturdy desk or table, and hold on until the shaking stops. The doorway myth is outdated — modern doorways are no stronger than other parts of a building. Running outside exposes you to falling debris."},
{id:65,cat:"priorities",q:"What should be your FIRST priority if you smell natural gas after an earthquake or disaster?",o:["Light a match to check where the leak is coming from so you can attempt to shut off the source of the gas if it is accessible","Call 911 immediately from inside the building using a landline or cell phone to report the gas leak to local emergency services","Leave the building immediately without using electrical switches, phones, or open flames, then call for help from outside","Open all windows and doors to ventilate the space thoroughly and wait for the gas smell to dissipate before investigating further"],a:2,src:"FEMA / Ready.gov — Earthquakes; U.S. Department of Energy — Natural Gas Safety",exp:"Natural gas is extremely flammable — any spark (light switch, phone, match) can cause an explosion. Evacuate immediately without touching electrical switches. Call 911 or your gas company from outside. Do not re-enter the building. Opening windows is insufficient and delays evacuation."},

// ═══════════════════════════════════════════════════
// ADDITIONAL QUESTIONS — 3 per category
// Top skills per category sourced from 2+ references
// ═══════════════════════════════════════════════════

// ── FOOD & NUTRITION ──
// Key skills: (1) Safe food handling without power (2) Food rationing (3) Identifying unsafe food
// Sources: USDA FoodSafety.gov, FEMA/Ready.gov, American Red Cross
{id:66,cat:"food",q:"According to the USDA, what is the maximum time perishable food can remain in the 'danger zone' (40°F–140°F) before it must be discarded?",o:["30 minutes","1 hour","2 hours","4 hours"],a:2,src:"USDA / FoodSafety.gov — Danger Zone; FDA — Food Safety During Emergencies",exp:"The USDA states perishable food should not remain between 40°F and 140°F for more than 2 hours (1 hour if the ambient temperature is above 90°F). After that, bacterial growth reaches unsafe levels regardless of how the food looks or smells."},
{id:67,cat:"food",q:"When rationing food in a survival situation, which macronutrient provides the most sustained energy per gram?",o:["Protein — 4 calories per gram","Carbohydrates — 4 calories per gram","Fat — 9 calories per gram","Fiber — 7 calories per gram"],a:2,src:"USDA Dietary Guidelines for Americans; U.S. Army FM 21-76 Survival Manual",exp:"Fat provides 9 calories per gram, more than double the 4 calories per gram from protein or carbohydrates. In survival rationing, calorie-dense fatty foods (peanut butter, nuts, oils) stretch supplies furthest. Fiber provides negligible calories."},
{id:68,cat:"food",q:"After a flood, the Red Cross says you should discard any food that has come in contact with floodwater EXCEPT which type?",o:["Canned goods with screw-top lids that appear undamaged after the flood","Fresh produce that can be thoroughly washed and peeled before eating","Undamaged commercially sealed cans that are cleaned and sanitized","Bread stored in sealed plastic bags that kept water out during flooding"],a:2,src:"American Red Cross — Food Safety After a Flood; USDA / FoodSafety.gov",exp:"Only undamaged, commercially sealed cans (not dented, swollen, or rusted) can be saved — wash them with soap and hot water, then sanitize with a bleach solution. All food in non-waterproof containers, including screw-top jars and plastic bags, must be discarded."},

// ── WATER ──
// Key skills: (1) Multiple purification methods (2) Water storage (3) Recognizing contamination
// Sources: CDC, EPA, FEMA/Ready.gov
{id:69,cat:"water",q:"The CDC recommends which concentration of household bleach for emergency water disinfection?",o:["Any bleach concentration works the same regardless of the sodium hypochlorite percentage","Bleach containing 5–9% sodium hypochlorite, unscented and free of additives","Only bleach labeled 'drinking water safe' that is sold specifically for that purpose","Industrial-strength bleach at 20% concentration diluted down to a safe ratio"],a:1,src:"CDC — Making Water Safe in an Emergency; EPA — Emergency Disinfection",exp:"The CDC specifies regular unscented household liquid bleach containing 5–9% sodium hypochlorite. Scented bleach, color-safe bleach, and bleach with added cleaners contain chemicals toxic for ingestion. Always check the label before using bleach for water treatment."},
{id:70,cat:"water",q:"How should you store water for long-term emergency use at home according to FEMA?",o:["In open containers in the garage for easy access during an emergency evacuation situation","In food-grade, sealed containers stored in a cool, dark place, replaced every 6 months","In glass bottles placed in direct sunlight to keep the water sterile through UV exposure","In any clean container — storage method and container material don't significantly matter"],a:1,src:"FEMA / Ready.gov — Water; CDC — Emergency Water Storage",exp:"FEMA recommends food-grade containers (BPA-free plastic or glass) with tight seals, stored in a cool dark place, and rotated every 6 months for self-treated water. Heat, light, and non-food-grade containers can leach chemicals or allow algae growth. Commercially bottled water lasts indefinitely."},
{id:71,cat:"water",q:"What is the minimum recommended amount of water to store per person per day for an infant or nursing mother?",o:["Half a gallon — same standard recommendation as anyone else","One gallon — the standard recommendation for all individuals","More than one gallon — they have increased fluid needs","Two cups — infants and nursing mothers need very little water"],a:2,src:"FEMA / Ready.gov — Water; American Academy of Pediatrics — Emergency Preparedness",exp:"FEMA notes that children, nursing mothers, and people who are ill may need significantly more than the standard one gallon per person per day. Nursing mothers require extra fluid for milk production, and formula preparation requires additional clean water beyond the baby's direct intake."},

// ── SHELTER ──
// Key skills: (1) Site selection (2) Insulation principles (3) Shelter-in-place procedures
// Sources: FEMA/Ready.gov, NPS, U.S. Army FM 21-76
{id:72,cat:"shelter",q:"When selecting a location for an emergency shelter in the wilderness, which terrain feature is most dangerous to camp near?",o:["A tree line at the edge of a meadow near a clearing","A lone tall tree on a ridge — attracts lightning","A flat area with good drainage and firm ground surface","A rock overhang that provides natural cover from weather"],a:1,src:"National Park Service — Lightning Safety; U.S. Army FM 21-76 Survival Manual — Shelter",exp:"Lone tall trees on exposed ridges are lightning magnets. The NPS specifically warns against sheltering under isolated trees during storms. Rock overhangs can be excellent shelter, tree lines provide wind protection, and flat drained ground is ideal — but isolated tall objects on high ground are the most dangerous."},
{id:73,cat:"shelter",q:"FEMA recommends designating a 'safe room' in your home for tornado protection. Which room characteristics are best?",o:["Large room with windows for visibility and monitoring the storm","A small, windowless interior room on the lowest floor","An exterior room on the top floor for quick escape access to the roof","The garage, because it has the strongest structural frame and walls"],a:1,src:"FEMA / Ready.gov — Tornadoes; FEMA P-320 — Taking Shelter from the Storm",exp:"FEMA specifies a small, windowless interior room on the lowest floor — bathrooms and closets are ideal because their small size and extra wall framing provide reinforcement. Windows shatter in tornado-force winds, top floors take the worst damage, and garages have large unsupported openings."},
{id:74,cat:"shelter",q:"In a cold survival shelter, where is most body heat lost if you're lying directly on the ground?",o:["Through the top of your head — 'you lose 40% of heat through your head'","Through your hands and feet primarily","Through conduction into the ground beneath you","Through respiration as you breathe"],a:2,src:"U.S. Army FM 21-76 Survival Manual; Wilderness Medical Society — Hypothermia Guidelines",exp:"Ground conduction is the primary heat thief when lying down, draining heat up to 25 times faster than still air. The '40% through your head' claim is a widely cited myth — it originated from a flawed 1950s military study where subjects wore insulated suits but no hats. Insulate beneath you first."},

// ── NAVIGATION ──
// Key skills: (1) Map/terrain reading (2) Dead reckoning and pacing (3) Natural navigation
// Sources: NOAA, U.S. Army FM 3-25.26, NPS
{id:75,cat:"navigation",q:"On a topographic map, closely spaced contour lines indicate what type of terrain?",o:["Flat, level ground with no elevation changes","A valley or depression between two ridges","Steep terrain — a cliff or sharp slope","A body of water such as a lake or stream"],a:2,src:"USGS — Topographic Map Symbols; U.S. Army FM 3-25.26 Map Reading and Land Navigation",exp:"Contour lines connect points of equal elevation. When they're packed tightly together, elevation changes rapidly over a short distance — indicating steep terrain. Widely spaced lines mean gentle slopes. This is fundamental to reading any topographic map."},
{id:76,cat:"navigation",q:"What is 'dead reckoning' in navigation?",o:["Using the stars and celestial bodies to find magnetic north and accurately determine your geographic position on a map","Estimating your current position based on your last known position, direction of travel, speed, and elapsed time","Following a stream or river to determine which direction is downhill and then toward potential settlements or main roads","Reading a compass bearing while walking in a straight line and carefully counting paces to measure distance traveled"],a:1,src:"NOAA — Navigation Basics; U.S. Army FM 3-25.26 Map Reading and Land Navigation",exp:"Dead reckoning means calculating your current position by starting from a known point and tracking direction, distance (often by pace count), and time traveled. It's the foundational navigation method when GPS fails and visibility is limited, and has been used by mariners and soldiers for centuries."},
{id:77,cat:"navigation",q:"At night in the Northern Hemisphere, how do you find true north using the stars?",o:["Follow the brightest star in the sky — it always marks north regardless of season","Locate the Big Dipper's pointer stars, which lead to Polaris (the North Star)","The constellation Orion's belt always points due north throughout the entire year","The moon always rises in the north and sets in the south in the Northern Hemisphere"],a:1,src:"NOAA — Celestial Navigation; U.S. Army FM 3-25.26 Map Reading and Land Navigation",exp:"The two stars at the front edge of the Big Dipper's 'cup' (Dubhe and Merak) point directly to Polaris, the North Star, which sits within 1° of true north. Polaris is not the brightest star — it's moderately bright. Orion's belt points roughly east-west, not north."},
{id:105,cat:"navigation",q:"In the shadow-stick method of navigation, you place a stick vertically in the ground and mark the tip of its shadow, then wait 15–30 minutes and mark the new shadow tip. What does the line between those two marks represent?",o:["A north-south line — the first mark is always north and the second mark is south","An approximate east-west line — the first mark is west, the second mark is east","A line pointing directly toward the sun's current position in the sky at that time of day","A line indicating magnetic north, similar to what a compass needle shows you"],a:1,src:"U.S. Army FM 3-25.26 Map Reading and Land Navigation; U.S. Air Force Survival Manual (AF 64-4)",exp:"As the sun moves east to west, shadows move in the opposite direction — west to east. The first shadow tip (Mark 1) points roughly west, the second (Mark 2) points roughly east. A line between them gives an approximate east-west line. A perpendicular line from that gives north-south. This method works anywhere the sun casts a shadow and requires no equipment except a stick and two markers.",media:{type:"image",url:"images/navigation-sun-stick.svg",alt:"Diagram showing the shadow-stick navigation method: a vertical stick casts shadows that are marked at two times to establish an east-west line",caption:"The shadow-stick method: Mark 1 (west) and Mark 2 (east) create an east-west reference line (Source: U.S. Army FM 3-25.26)"}},

// ── EMERGENCY COMMUNICATIONS ──
// Key skills: (1) Emergency messaging protocols (2) Radio basics (3) Alternative communication
// Sources: FCC, FEMA/Ready.gov, NOAA
{id:78,cat:"comms",q:"When calling 911 from a cell phone, what critical limitation should you be aware of?",o:["Cell phones cannot call 911 — only landlines work for connecting to emergency dispatch services","Your location may not transmit accurately to the dispatcher — be prepared to state it verbally","911 calls from cell phones are always deprioritized in favor of landline calls to the same center","Cell phones can only reach 911 within 5 miles of a tower, so rural coverage is extremely limited"],a:1,src:"FCC.gov — 911 Wireless Services; NENA (National Emergency Number Association)",exp:"Unlike landlines, cell phones don't automatically transmit a precise address to 911 dispatchers. While GPS-based location (Enhanced 911) is improving, it can be inaccurate by hundreds of meters, especially indoors. Always state your location clearly and verbally when calling 911 from a mobile phone."},
{id:79,cat:"comms",q:"FRS (Family Radio Service) walkie-talkies require no license to operate. What is their realistic communication range in wooded or hilly terrain?",o:["Up to 36 miles as advertised on the packaging","Typically half a mile to 2 miles","About 10 to 15 miles","Only a few hundred feet"],a:1,src:"FCC.gov — FRS Radio Service Rules; ARRL — VHF/UHF Communication",exp:"Despite packaging claims of 20-36 miles (which assume flat open terrain with no obstructions), real-world FRS range in woods or hills is typically 0.5 to 2 miles. Trees, terrain, and buildings dramatically reduce UHF radio range. Manage expectations accordingly when relying on FRS for emergency communication."},
{id:80,cat:"comms",q:"What does the FEMA 'IPAWS' system allow authorities to do during a large-scale emergency?",o:["Shut down all cell phone networks to prevent congestion and reserve bandwidth for first responders","Send emergency alerts simultaneously through cell phones, radio, TV, and internet services","Track the real-time location of every cell phone in the disaster area to coordinate rescue efforts","Automatically dispatch first responders to every 911 call without requiring human operator review"],a:1,src:"FEMA — Integrated Public Alert and Warning System (IPAWS); FCC — Emergency Alert System",exp:"IPAWS (Integrated Public Alert and Warning System) allows authorized officials to send one alert that simultaneously reaches people through Wireless Emergency Alerts (WEA), the Emergency Alert System (TV/radio), and NOAA Weather Radio. It's the backbone of the national alerting infrastructure."},

// ── RESCUE ──
// Key skills: (1) Visual signaling technique (2) Self-rescue vs wait decision (3) Helicopter interaction
// Sources: U.S. Air Force Survival Manual, U.S. Coast Guard, NPS
{id:81,cat:"rescue",q:"A signal fire should produce what kind of smoke for maximum daytime visibility?",o:["Black smoke — it's always more visible against any background or sky conditions","White or light-colored smoke — it contrasts best against most terrain and sky","No smoke — a clean-burning fire with tall bright flames is far more visible","Red-tinted smoke from burning certain plastics or synthetic rubber materials"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4); U.S. Army FM 21-76 Survival Manual",exp:"White/light smoke (produced by adding green vegetation, moss, or damp material to a hot fire) provides the best contrast against dark terrain. Against snow or overcast skies, dark smoke (from burning rubber or oil) is better. Adapt your smoke to contrast with your background. Clean-burning fires produce minimal visible smoke."},
{id:82,cat:"rescue",q:"When a rescue helicopter is approaching, what should you do about loose items in the landing zone?",o:["Pile them near the helicopter for easy loading once the aircraft has safely landed","Secure or remove all loose items — rotor wash can turn them into deadly projectiles","Wave them above your head to attract the pilot's attention as the helicopter approaches","Nothing — helicopter pilots are trained to avoid debris and will adjust their approach"],a:1,src:"U.S. Coast Guard — Helicopter Rescue Operations; NPS — Helicopter Safety for Ground Personnel",exp:"Helicopter rotor wash generates winds of 60-100+ mph. Loose clothing, tarps, branches, backpacks, and even gravel become dangerous projectiles. Secure everything, wear eye protection if available, and keep low when approaching. Approach only from the front/side on the downhill side, never from the rear near the tail rotor."},
{id:83,cat:"rescue",q:"The international distress signal using a whistle is three blasts. How should the blasts be spaced?",o:["Three rapid blasts with no pause between them fired in quick succession","Three blasts evenly spaced, repeated every minute until acknowledged","One long continuous blast lasting three seconds followed by silence","Three blasts followed by a 10-minute rest period before repeating"],a:1,src:"National Park Service — Hiking Safety; International Convention for the Safety of Life at Sea (SOLAS)",exp:"Three evenly spaced blasts repeated at regular intervals (approximately every minute) is the standard. The even spacing distinguishes it from random noise. Two blasts is the standard response meaning 'signal received.' Continue signaling until rescue makes contact."},

// ── FIRST AID ──
// Key skills: (1) Severe bleeding control (2) Airway management (3) Wound infection prevention
// Sources: American Heart Association, American Red Cross, CDC
{id:84,cat:"first-aid",q:"What is the correct order of steps when applying a commercial tourniquet for life-threatening limb bleeding?",o:["Apply loosely to slow blood flow, then tighten gradually over 10 minutes while monitoring the patient's response","Place 2-3 inches above the wound, tighten until bleeding stops, note the time, and do NOT remove it","Apply directly over the wound and twist the windlass until the entire limb goes completely numb below the point","Apply below the wound (between the wound and the hand/foot) and tighten fully to trap venom or blood at the site"],a:1,src:"American Red Cross — First Aid/CPR/AED Manual; American College of Surgeons — Stop the Bleed",exp:"Place the tourniquet 2-3 inches above the wound (between the wound and the heart), tighten the windlass until bleeding stops, lock it, and write the time of application on the tourniquet or the patient's skin. Never remove a tourniquet in the field — that's a hospital decision. 'Stop the Bleed' is now a national campaign teaching civilians this skill."},
{id:85,cat:"first-aid",q:"If someone is unconscious but breathing normally, what position should you place them in?",o:["Flat on their back with legs elevated above the level of the heart","Sitting upright supported against a wall with their head tilted forward","The recovery position — on their side with the top knee bent forward","Flat on their stomach face-down with their head turned to one side"],a:2,src:"American Red Cross — First Aid/CPR/AED Manual; American Heart Association — First Aid Guidelines",exp:"The recovery position (lateral recumbent) keeps the airway open and allows fluids to drain from the mouth, preventing aspiration. An unconscious person on their back risks choking on vomit or having the tongue block the airway. Do NOT use the recovery position if spinal injury is suspected."},
{id:86,cat:"first-aid",q:"When cleaning a wound in a survival situation with limited supplies, what does the Red Cross recommend as the best improvised irrigation method?",o:["Pour alcohol or hydrogen peroxide directly into the wound","Apply a poultice of mud or plant material to draw out infection","Flush the wound with large amounts of clean drinkable water under pressure","Let the wound air-dry without cleaning — your body's immune system will handle it"],a:2,src:"American Red Cross — Wilderness First Aid; Wilderness Medical Society — Wound Management Guidelines",exp:"Irrigation with clean water under gentle pressure (squeezing from a water bottle) is the most effective field method to remove debris and bacteria. Alcohol and hydrogen peroxide damage healthy tissue and delay healing. Mud introduces bacteria. The volume of water matters more than what's in it — flush generously."},

// ── SURVIVAL PSYCHOLOGY ──
// Key skills: (1) Stress inoculation (2) Group morale management (3) Decision-making under fatigue
// Sources: U.S. Air Force Survival Manual, U.S. Army FM 6-22, APA
{id:87,cat:"psychology",q:"What is 'stress inoculation' and why do military survival schools use it?",o:["Injecting personnel with stress hormones to build physiological immunity to panic and anxiety responses","Exposing people to controlled, escalating stressors so they develop coping strategies before a real crisis","Teaching people to suppress all emotional responses in emergencies through disciplined mental conditioning","Removing all stress from training environments to prevent burnout and preserve long-term psychological health"],a:1,src:"U.S. Air Force SERE School Manual; American Psychological Association — Building Resilience",exp:"Stress inoculation training (SIT) deliberately exposes people to graduated stress in a controlled setting so they develop coping mechanisms that transfer to real emergencies. The principle: if you've practiced making decisions while cold, hungry, and tired, you'll perform better when it happens for real. This is why realistic training outperforms classroom learning."},
{id:88,cat:"psychology",q:"When a group's morale is collapsing in a survival situation, what does research show is the most effective immediate intervention?",o:["Tell everyone to stay positive and suppress negative feelings to maintain group cohesion","Assign each person a specific, achievable task that contributes to group survival","Isolate the most negative person from the group to prevent morale from spreading","Have everyone rest and avoid all activity until morale improves on its own naturally"],a:1,src:"U.S. Army FM 6-22 — Leader Development; U.S. Air Force Survival Manual (AF 64-4) — Psychology of Survival",exp:"Purposeful activity combats helplessness — the primary driver of morale collapse. Assigning specific tasks (gather firewood, monitor the patient, inventory supplies) gives people agency, structure, and a sense of contribution. Suppressing emotions backfires. Isolation breeds resentment. Inactivity deepens despair."},
{id:89,cat:"psychology",q:"Sleep deprivation severely impairs decision-making. After how many hours without sleep does cognitive performance drop to the equivalent of legal intoxication?",o:["About 12 hours of continuous wakefulness","About 17–19 hours","About 36 hours of continuous wakefulness","About 48 hours of continuous wakefulness"],a:1,src:"CDC — Sleep and Sleep Disorders; NIH/National Institute of Neurological Disorders — Brain Basics: Sleep",exp:"Research cited by the CDC shows that after 17-19 hours without sleep, cognitive and motor performance is equivalent to a blood alcohol concentration of 0.05%, and after 24 hours it approaches 0.10% (above the legal limit in all U.S. states). In survival situations, this means designating rest periods is not a luxury — it's a safety-critical decision."},

// ── FIRE, CLOTHING & EQUIPMENT ──
// Key skills: (1) Fire in wet conditions (2) Material properties for protection (3) Improvised tools
// Sources: U.S. Army FM 21-76, U.S. Air Force Survival Manual, Red Cross
{id:90,cat:"fire-clothing",q:"In wet conditions, where should you look for dry fire-starting material?",o:["Under large rocks — they stay dry and sheltered underneath","Dead standing branches and the dry inner wood of split logs","In the topsoil — dig down 6 inches where it is always dry","Green living branches — they burn hotter than dead dry wood"],a:1,src:"U.S. Army FM 21-76 Survival Manual — Fire Building; U.S. Air Force Survival Manual (AF 64-4)",exp:"Dead standing wood (still attached to the tree, off the ground) is the most reliable dry fuel source in wet conditions because it sheds rain and doesn't absorb ground moisture. Splitting open logs exposes dry inner wood. Ground material is typically saturated. Green wood contains too much moisture to burn efficiently."},
{id:91,cat:"fire-clothing",q:"What property makes wool a superior survival fabric compared to cotton?",o:["Wool is lighter and more packable than cotton, making it ideal for long-distance travel","Wool retains up to 80% of its insulating value when wet; cotton retains almost none","Wool is completely waterproof and repels all moisture including rain and heavy condensation","Wool is more durable than cotton and virtually never wears out under normal field use"],a:1,src:"U.S. Army FM 21-76 Survival Manual; American Red Cross — Cold Weather Safety",exp:"Wool fibers trap air even when wet, retaining approximately 80% of their insulating ability. Cotton absorbs water, collapses flat, and conducts heat away from the body — earning the survival saying 'cotton kills.' Modern synthetic fleece performs similarly to wool but melts near flame, while wool chars and self-extinguishes."},
{id:92,cat:"fire-clothing",q:"A vehicle's side-view mirror can be repurposed in a survival situation for what critical use?",o:["As a cutting tool — the glass edges are sharp enough for slicing","As a signal mirror to reflect sunlight toward rescuers","As a water container when carefully removed from the housing","As a fire reflector to direct heat into a shelter or sleeping area"],a:1,src:"U.S. Air Force Survival Manual (AF 64-4) — Improvised Signaling; U.S. Army FM 21-76",exp:"A vehicle mirror is an excellent improvised signal mirror — it can reflect sunlight visible up to 10 miles away on a clear day, far outperforming waving or shouting. Any reflective surface (CD, phone screen, belt buckle, aluminum foil) can serve this purpose in an emergency, but a flat mirror is ideal."},

// ── PLANNING & PREPARATION ──
// Key skills: (1) Risk assessment for your region (2) Document and financial preparedness (3) Practice and drills
// Sources: FEMA/Ready.gov, Red Cross, DHS
{id:93,cat:"planning",q:"FEMA recommends keeping copies of critical documents in your emergency kit. Which document is MOST important for disaster recovery?",o:["Your birth certificate only, stored in a waterproof bag with your emergency kit supplies at all times","Proof of identity plus proof of home ownership or rental agreement (insurance policies, lease, deed)","Your vehicle registration and title documents along with current maintenance and inspection records","Your college diploma and professional certifications needed to verify employment after a disaster"],a:1,src:"FEMA / Ready.gov — Important Documents; American Red Cross — Emergency Preparedness",exp:"After a disaster, proof of identity and proof of residence/ownership are essential for accessing FEMA aid, insurance claims, shelter services, and returning to restricted areas. FEMA recommends keeping copies of: government-issued ID, insurance policies, bank account records, and property documents in a waterproof, portable container."},
{id:94,cat:"planning",q:"How does FEMA recommend you determine which hazards to prioritize in your emergency plan?",o:["Plan only for the single most likely disaster in your area based on historical frequency data, local climate patterns, and regional geography","Research your area's specific risks at Ready.gov and your local emergency management agency, then plan for the most likely and most impactful","Prepare equally for all possible disasters regardless of probability, creating individual detailed response plans and supply kits for each potential scenario","Only plan for hazards you've personally experienced before, since those represent the most statistically realistic threats to your specific area and household"],a:1,src:"FEMA / Ready.gov — Be Informed; DHS — National Risk Index",exp:"FEMA's approach is risk-based: identify which hazards actually affect your specific region (hurricanes, earthquakes, wildfires, floods, winter storms) through Ready.gov and local emergency management, then prioritize preparation for those with the highest probability and impact. The National Risk Index at hazards.fema.gov provides county-level risk data."},
{id:95,cat:"planning",q:"What does FEMA recommend families do at least twice a year regarding their emergency plan?",o:["Replace all food and water supplies completely with fresh stock","Conduct a practice drill so all family members know what to do","Re-watch FEMA training videos online to refresh your knowledge","Send an updated plan to FEMA headquarters for review and filing"],a:1,src:"FEMA / Ready.gov — Make a Plan; American Red Cross — Home Emergency Preparedness",exp:"FEMA and the Red Cross both recommend conducting practice drills at least twice a year — including practicing evacuation routes, testing meeting-point plans, and verifying everyone knows how to shut off utilities. A plan that hasn't been practiced is just a document. Drills reveal gaps you can't find by reading."},

// ── HAZARDS & PPE ──
// Key skills: (1) Hazardous material recognition (2) Improvised respiratory protection (3) Decontamination basics
// Sources: CDC, OSHA, FEMA
{id:96,cat:"hazards-ppe",q:"During a volcanic eruption, what is the primary health hazard from ashfall?",o:["Burns from hot volcanic rock fragments raining down on exposed areas","Respiratory damage from inhaling fine silica glass particles","Radiation exposure from volcanic minerals brought up from deep underground","Poisoning from sulfuric acid and toxic chemical compounds present in the ash"],a:1,src:"CDC — Volcanic Ash: Health Hazards; USGS — Volcano Hazards Program",exp:"Volcanic ash is not soft like wood ash — it's made of tiny jagged glass and mineral particles that can cause serious lung damage when inhaled, especially for people with existing respiratory conditions. The CDC recommends N95 masks, wetting ash before sweeping, and staying indoors with windows sealed during heavy ashfall."},
{id:97,cat:"hazards-ppe",q:"If you encounter a chemical spill with an unknown substance, what is the recommended minimum safe distance for initial isolation according to the Emergency Response Guidebook?",o:["10 feet in any direction from the visible edge of the chemical spill","At least 330 feet (100 meters) in all directions as a starting point","1 mile upwind only, with no specific minimum distance in other directions","50 feet uphill from the spill and well away from any drainage path"],a:1,src:"DOT / PHMSA — Emergency Response Guidebook (ERG); OSHA — Hazardous Materials Emergency Response",exp:"The ERG (carried by every first responder in the U.S.) recommends a minimum initial isolation distance of 330 feet (100 meters) in all directions for unknown substances, moving upwind and uphill. This is a starting point — the actual safe distance depends on the specific material, quantity, and weather conditions."},
{id:98,cat:"hazards-ppe",q:"What does OSHA identify as the most common cause of death in confined spaces like wells, tanks, and silos?",o:["Structural collapse of the space caused by vibration or pressure changes","Oxygen-deficient atmospheres — victims lose consciousness without warning","Extreme heat trapped inside enclosed spaces that causes rapid dehydration","Toxic contact with chemically coated surfaces that causes skin absorption"],a:1,src:"OSHA — Confined Space Entry / Permit-Required Confined Spaces; CDC/NIOSH — Confined Space Fatalities",exp:"Oxygen displacement (by gases like CO2, methane, or nitrogen) is the #1 killer in confined spaces. Victims often collapse without warning because the body cannot detect low oxygen the way it detects CO2 buildup. A tragic pattern: one person collapses, a rescuer enters without air monitoring and also collapses. Never enter a confined space without testing the atmosphere."},

// ── CAMPCRAFT ──
// Key skills: (1) Hygiene and sanitation (2) Knots and lashing (3) Weather reading
// Sources: NPS, U.S. Army FM 21-76, CDC
{id:99,cat:"campcraft",q:"In a wilderness survival camp, how far from your water source and campsite should you establish a latrine?",o:["Anywhere is fine as long as you bury waste at a depth of at least several inches","At least 200 feet from water sources, camp, and trails, in a hole 6–8 inches deep","At least 20 feet from camp in a shallow scrape, no deep hole needed for breakdown","At least 50 feet from camp, deposited in running water to flush waste away safely"],a:1,src:"Leave No Trace Center for Outdoor Ethics; NPS — Backcountry Waste Disposal; CDC — Wilderness Sanitation",exp:"The 200-foot (70-step) minimum from water, camp, and trails prevents water contamination and disease transmission. The 6-8 inch depth places waste in biologically active soil for faster decomposition while preventing animal digging. Never deposit waste in water — even flowing water carries pathogens downstream to other users."},
{id:100,cat:"campcraft",q:"Which basic knot is most essential for wilderness survival because it creates a fixed loop that won't slip under load?",o:["The square knot — best for tying two ropes together","The bowline — creates a secure, non-slipping loop","The granny knot — the strongest all-purpose knot","The slip knot — easy to tie and untie"],a:1,src:"U.S. Army FM 21-76 Survival Manual — Knots and Lashing; NPS — Wilderness Skills",exp:"The bowline ('king of knots') creates a fixed loop that will not slip or tighten under load but remains easy to untie. It's used for rescue harnesses, securing shelter ridgelines, hanging bear bags, and tying to anchor points. The square knot joins two ropes but can capsize under uneven load. A granny knot is an incorrectly tied square knot."},
{id:101,cat:"campcraft",q:"Rapidly dropping barometric pressure combined with increasing wind typically indicates what weather change?",o:["Clear skies and warming temperatures approaching within the next several hours","A storm system approaching — expect deteriorating conditions within hours","Temperature inversion causing fog and calm conditions at lower elevations","A high-pressure system bringing stable weather and clearing skies for days"],a:1,src:"NOAA / National Weather Service — Weather Observation; U.S. Army FM 21-76 Survival Manual — Weather Prediction",exp:"Falling barometric pressure is the most reliable natural indicator of approaching bad weather. Combined with increasing wind and building clouds, it signals a frontal system that typically brings precipitation within 12-24 hours. Rising pressure indicates clearing. If you have an altimeter watch, an unexplained altitude increase while stationary means pressure is dropping."},

// ── SURVIVAL PRIORITIES ──
// Key skills: (1) Triage skills (2) Resource management (3) Situational assessment
// Sources: FEMA CERT Manual, U.S. Forest Service, American Red Cross
{id:102,cat:"priorities",q:"In CERT triage, what does a RED tag mean?",o:["The person is dead and cannot be helped — no further medical attention is warranted","The person has minor injuries and can wait for treatment at a later triage station","The person has an immediate life threat that is survivable with prompt intervention","The person's injuries are beyond help given available resources and current conditions"],a:2,src:"FEMA — CERT Basic Training Manual, Unit 3: Triage; American Red Cross — First Aid Triage",exp:"RED = Immediate: life-threatening conditions that are survivable with prompt intervention (severe bleeding, airway compromise, shock). YELLOW = Delayed: serious but can wait. GREEN = Minor: walking wounded. BLACK = Expectant: unlikely to survive or already deceased. The goal is to do the greatest good for the greatest number."},
{id:103,cat:"priorities",q:"You have limited water, a injured person, and failing daylight. According to survival priority principles, which do you address first?",o:["Water — dehydration can kill in 3 days","The injured person — medical emergencies always come first","Shelter and warmth — exposure can kill in 3 hours","Signaling for rescue — help solves all problems"],a:2,src:"U.S. Forest Service — Wilderness Survival; U.S. Air Force Survival Manual (AF 64-4) — Priorities",exp:"The Rule of Threes drives the answer: exposure (3 hours) kills faster than dehydration (3 days). Stabilize the injured person's immediate life threats (bleeding, airway), then secure shelter and warmth for everyone before addressing water. Signaling is important but won't help if you succumb to hypothermia overnight."},
{id:104,cat:"priorities",q:"After ensuring personal safety in a disaster, what does FEMA's CERT program teach as the next priority before helping others?",o:["Document the damage for insurance purposes before disturbing anything at the scene","Size up the situation — assess hazards, count victims, determine available resources","Begin treating the most severely injured person immediately without delay or hesitation","Call the media to report the situation and request that additional assistance be dispatched"],a:1,src:"FEMA — CERT Basic Training Manual, Unit 1: Disaster Preparedness; American Red Cross — Disaster Response",exp:"CERT teaches: after ensuring your own safety, size up the entire situation before acting. Count victims, identify hazards (gas leaks, structural damage, downed power lines), assess available resources, and form a plan. Rushing to treat one victim without assessing the scene can lead you into hazards or cause you to miss someone in worse condition."}
];
